# Generated by Django 5.1.6 on 2025-02-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="arquivo",
            field=models.FileField(blank=True, null=True, upload_to="arquivos/"),
        ),
        migrations.AddField(
            model_name="item",
            name="data_adicao",
            field=models.DateField(auto_now_add=True, default="2011-09-01"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="data_original",
            field=models.DateField(blank=True, null=True),
        ),
    ]
